apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa
  namespace: api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tripviewer-deployment
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50