apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer-deployment
  labels:
    app: tripviewer
  namespace: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: tripviewer
        image: registryujx8519.azurecr.io/tripviewer:vk
        resources:
          requests:
            memory: "400Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 80
        livenessProbe:
            httpGet:
                path: /
                port: 80
        env:
          - name: TRIPS_API_ENDPOINT
            value: http://trips
          - name: USERPROFILE_API_ENDPOINT
            value: http://userprofile
---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer
  namespace: api
spec:
  selector:
    app: tripviewer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 